# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tJQ9mJi28sUlMrYD7tRA5HNTGaVKNuNv
"""

def isPrime(num):
  for i in range(2,num):
    if (num % i) == 0:
      n=random.randint(2,101)
      return isPrime(n)
    return num

matrix = [[0 for x in range(3)] for y in range(3)]

for i in range(3):
 for j in range(3):
    n=random.randint(2,101)
    matrix[i][j]=isPrime(n)
for i in range(len(matrix)):
  for j in range(len(matrix[i])):
    print(matrix[i][j],end='        ')
  print()